### ISSUE TITLE
[Feature] Better error message for non-existing accounts

### ISSUE THREAD

**Issue by thomasmenneckemeyer** [mskg/tabler-world-mobile#164]
Because of the international usage, a lot of Tabler want to login, which does not have a member function in Tabler.World.

Therefore it would be good to change the error message when a login is failing 

![image](https://user-images.githubusercontent.com/51943349/79556410-560cf080-80a1-11ea-8ce0-565b337ec86f.jpeg)

So we should add, that a Tabler world Account and a valid member function must be available

**Comment by mskg** [comment]
What about: `You need to be an active member and have a valid TABLER.WORLD membership. Please sign-in with your '@xxxx.roundtable.world' e-mail address.`

**Comment by thomasmenneckemeyer** [comment]
Much better.
Write “active member”, the rest is perfect
